runtime: python312  # or the latest Python 3 runtime

entrypoint: gunicorn -w 4 main:app  # This will use Gunicorn with 4 workers to serve the app

handlers:
- url: /.*
  script: auto

instance_class: F2


env_variables:
  GOOGLE_CLIENT_ID: ''
  GOOGLE_CLIENT_SECRET: ''
  FLASK_SECRET_KEY: ''
  GOOGLE_CLOUD_PROJECT: "transformers-200"
  BUCKET_NAME: "etl_complexity_tool_src"
  BQ_DATASET: "etl_mig"
  METADATA_TABLE: "uploads_metadata"
  TABLE_NAMES: "raw_etl_mappings_data_new,src_etl_map_tgt_tbl_new,src_etl_tbl_sizes_new"  # Comma-separated table names
